### ISSUE TITLE
Non privileged user

### ISSUE THREAD

**Issue by rjalexa** [thehale/docker-python-poetry#4]
First of all thanks a lot for this little life saver :) My to go from now on for my FastAPI microservices.

Would you consider creating a non privileged user that we can then use to run our projects?

The Node image does that for example and it defines a node:node with UID 1000

Take care !!!

**Comment by thehale** [comment]
Happy to accept a PR for this request that fulfills the following:
- [ ] Creates the user account in the image.
- [ ] Adds written documentation explaining how to use the image.

For now, I do *not* want the non-root user activated by default so as to maintain backward compatibility with other users of this image. As Poetry releases new versions, we may choose to enable the non-root user by default.

---

**Implementation Guide**

Looks like this is the key line from the [Node Dockerfile](https://github.com/nodejs/docker-node/blob/2928850549388a57a33365302fc5ebac91f78ffe/Dockerfile-debian.template#L3-L4) that we'd need to adapt for usage in this project.

```
RUN groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node
```

And here's the link to the relevant documentation for Node (which we'd want to replicate in some form in this project): https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user

**Comment by rjalexa** [comment]
yeah that, and personally I would name the user notroot but it's a matter of preferences :) Thanks a lot.
